name = "titanvip"
main = "worker.js"
compatibility_date = "2025-12-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "titanvip"
database_id = "d2c95304-7a14-4e96-b3db-94f8b160e9d4"

[triggers]
crons = ["30 * * * *"]
