name = "titan"
main = "worker.js"
compatibility_date = "2025-12-01"

[[d1_databases]]
binding = "DB"
database_name = "vip_db"
database_id = "d2c95304-7a14-4e96-b3db-94f8b160e9d4"

[triggers]
# هر ۱ ساعت یکبار، سرِ ساعت تهران
# چون تهران UTC+3:30 هست، دقیقه 30 UTC = دقیقه 00 تهران
crons = ["30 * * * *"]
